# Generated by Django 4.0 on 2022-01-27 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('C_Name', models.CharField(blank=True, max_length=60)),
                ('Flag', models.IntegerField(default=0, max_length=2)),
                ('Count', models.IntegerField(default=0, max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_Name', models.CharField(max_length=60)),
                ('Flag', models.IntegerField(default=0, max_length=2)),
                ('Count', models.IntegerField(default=0, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_Name', models.CharField(blank=True, max_length=60)),
                ('Flag', models.IntegerField(default=0, max_length=2)),
                ('Count', models.IntegerField(default=0, max_length=6)),
                ('Sub_Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data_link', models.URLField(blank=True)),
                ('Count', models.IntegerField(default=0, max_length=6)),
                ('Link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.sub_category')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.fields'),
        ),
    ]
