# Generated by Django 4.0 on 2022-01-27 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_fields_sub_category_link_category_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='C_Name',
            new_name='Category_Name',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='Category',
            new_name='FieldFK',
        ),
        migrations.RenameField(
            model_name='fields',
            old_name='F_Name',
            new_name='Field_Name',
        ),
        migrations.RenameField(
            model_name='link',
            old_name='Link',
            new_name='Sub_CategoryFK',
        ),
        migrations.RenameField(
            model_name='sub_category',
            old_name='Sub_Category',
            new_name='CategoryFK',
        ),
        migrations.RenameField(
            model_name='sub_category',
            old_name='S_Name',
            new_name='Sub_Name',
        ),
    ]
