# Generated by Django 4.0 on 2022-02-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_c_name_category_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='link_description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
